# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
command_timeout = 1000

[directory]
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
# symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
symbol = ' '

[golang]
symbol = ' '
format = '[$symbol($version )]($style)'

[haskell]
symbol = ' '

[rust]
symbol = ' '

[ruby]
symbol = ' '

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile', 'compose.yml', 'compose.yaml']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
format = '[$duration]($style)'

